[api]
port = 54321
schemas = ["public"]

[db]
port = 54322
major_version = 17

[studio]
port = 54323

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000/auth/callback"]

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
